require("sm00k3y.plugins-setup")
require("sm00k3y.core.options")
require("sm00k3y.core.colorscheme")
require("sm00k3y.core.keymaps")
require("sm00k3y.plugins.comment")
require("sm00k3y.plugins.nvim-tree")
require("sm00k3y.plugins.lualine")
require("sm00k3y.plugins.telescope")
require("sm00k3y.plugins.lsp.lsp-saga")
require("sm00k3y.plugins.lsp.lsp")
-- require("sm00k3y.plugins.lsp.mason-null-ls")
require("sm00k3y.plugins.lsp.null-ls")
require("sm00k3y.plugins.autopairs")
require("sm00k3y.plugins.treesitter")
require("sm00k3y.plugins.gitsigns")
